### ISSUE TITLE
strange error with nesthostclass

### ISSUE THREAD

**Issue by Xplodin** [Loli-Server/LoliServer1.16#217]
**Minecraft Version(我的世界版本) :** {Minecraft version}
1.16.5
**LoliServer buildVersion(构建版本) :** {Provide LoliServer build number}
109
**Operating System(操作系统) :** {Provide the name of your OS}
Ubuntu 18.04
**Logs :** {Link(s) of logs and crash reports if you have}, (https://paste.loliidc.cn)
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
:/home/container$ java -Xms128M -Xmx16386M -jar server.jar
.____ .__ .__ _________
| | ____ | | |__|/ _____/ ______________ __ ___________
| | / _ \| | | |\_____ \_/ __ \_ __ \ \/ // __ \_ __ \
| |__( <_> ) |_| |/ \ ___/| | \/\ /\ ___/| | \/
|_______ \____/|____/__/_______ /\___ >__| \_/ \___ >__|
\/ \/ \/ \/
Welcome to LoliServer 1.16.5 ! - LoliServer Developement Group
[00:54:52][INFO]: The Java version verification is completed, and the LoliServer process will continue
Global percentage >0%
Downloading file unsafe-0.2.0.jar with size 2.7675781 KB
Download finished for unsafe-0.2.0.jar !
Global percentage >1%
Downloading file j2objc-annotations-1.1.jar with size 8.576172 KB
Download finished for j2objc-annotations-1.1.jar !
Global percentage >3%
Downloading file asm-commons-6.1.1.jar with size 75.92285 KB
Download finished for asm-commons-6.1.1.jar !
Global percentage >5%
Downloading file grossjava9hacks-1.3.3.jar with size 2.0634766 KB
Download finished for grossjava9hacks-1.3.3.jar !
Global percentage >7%
Downloading file guava-25.1-jre.jar with size 2.6076689MB
Download finished for guava-25.1-jre.jar !
Global percentage >8%
Downloading file trove-1.0.2.jar with size 352.69043 KB
Download finished for trove-1.0.2.jar !
Global percentage >10%
Downloading file jansi-1.18.jar with size 280.6172 KB
Download finished for jansi-1.18.jar !
Global percentage >12%
Downloading file mcp_config-1.16.5-20210115.111550.zip with size 759.4258 KB
Download finished for mcp_config-1.16.5-20210115.111550.zip !
Global percentage >14%
Downloading file eventbus-4.0.0.jar with size 41.868164 KB
Download finished for eventbus-4.0.0.jar !
Global percentage >15%
Downloading file json-simple-1.1.1.jar with size 23.370117 KB
Download finished for json-simple-1.1.1.jar !
Global percentage >17%
Downloading file accesstransformers-3.0.1.jar with size 74.791016 KB
Download finished for accesstransformers-3.0.1.jar !
Global percentage >19%
Downloading file jline-3.12.1.jar with size 715.74805 KB
Download finished for jline-3.12.1.jar !
Global percentage >21%
Downloading file forgespi-3.2.0.jar with size 19.699219 KB
Download finished for forgespi-3.2.0.jar !
Global percentage >22%
Downloading file log4j-iostreams-2.11.2.jar with size 46.586914 KB
Download finished for log4j-iostreams-2.11.2.jar !
Global percentage >24%
Downloading file commons-lang-2.6.jar with size 277.5586 KB
Download finished for commons-lang-2.6.jar !
Global percentage >26%
Downloading file error_prone_annotations-2.1.3.jar with size 13.3828125 KB
Download finished for error_prone_annotations-2.1.3.jar !
Global percentage >28%
Downloading file minecraft_server.1.16.5.jar with size 36.203728MB
Downloading minecraft_server.1.16.5.jar - 0%
Downloading minecraft_server.1.16.5.jar - 30%
Downloading minecraft_server.1.16.5.jar - 39%
Downloading minecraft_server.1.16.5.jar - 49%
Downloading minecraft_server.1.16.5.jar - 59%
Downloading minecraft_server.1.16.5.jar - 69%
Downloading minecraft_server.1.16.5.jar - 79%
Downloading minecraft_server.1.16.5.jar - 89%
Download finished for minecraft_server.1.16.5.jar !
Global percentage >29%
Downloading file animal-sniffer-annotations-1.14.jar with size 3.4003906 KB
Download finished for animal-sniffer-annotations-1.14.jar !
Global percentage >31%
Downloading file SpecialSource-1.8.5.jar with size 79.27637 KB
Download finished for SpecialSource-1.8.5.jar !
Global percentage >33%
Downloading file gson-2.8.0.jar with size 226.51562 KB
Download finished for gson-2.8.0.jar !
Global percentage >35%
Downloading file guava-20.0.jar with size 2.3294687MB
Download finished for guava-20.0.jar !
Global percentage >36%
Downloading file terminalconsoleappender-1.2.0.jar with size 15.602539 KB
Download finished for terminalconsoleappender-1.2.0.jar !
Global percentage >38%
Downloading file checker-qual-2.0.0.jar with size 335.17773 KB
Download finished for checker-qual-2.0.0.jar !
Global percentage >40%
Downloading file mixin-0.8.4.jar with size 970.2549 KB
Download finished for mixin-0.8.4.jar !
Global percentage >42%
Downloading file maven-artifact-3.6.3.jar with size 56.46875 KB
Download finished for maven-artifact-3.6.3.jar !
Global percentage >43%
Downloading file sqlite-jdbc-3.34.0.jar with size 6.9583216MB
Download finished for sqlite-jdbc-3.34.0.jar !
Global percentage >45%
Downloading file snakeyaml-1.27.jar with size 302.83594 KB
Download finished for snakeyaml-1.27.jar !
Global percentage >47%
Downloading file core-3.6.3.jar with size 194.4248 KB
Download finished for core-3.6.3.jar !
Global percentage >49%
Downloading file asm-tree-6.1.1.jar with size 48.876953 KB
Download finished for asm-tree-6.1.1.jar !
Global percentage >50%
Downloading file toml-3.6.3.jar with size 30.554688 KB
Download finished for toml-3.6.3.jar !
Global percentage >52%
Downloading file fastcsv-1.0.2.jar with size 15.754883 KB
Download finished for fastcsv-1.0.2.jar !
Global percentage >54%
Downloading file log4j-api-2.11.2.jar with size 260.042 KB
Download finished for log4j-api-2.11.2.jar !
Global percentage >56%
Downloading file mysql-connector-java-5.1.49.jar with size 983.3047 KB
Download finished for mysql-connector-java-5.1.49.jar !
Global percentage >57%
Downloading file bungeecord-chat-1.16-R0.4.jar with size 145.49023 KB
Download finished for bungeecord-chat-1.16-R0.4.jar !
Global percentage >59%
Downloading file javaxdelta-2.0.1.jar with size 38.081055 KB
Download finished for javaxdelta-2.0.1.jar !
Global percentage >61%
Downloading file jarsplitter-1.1.2.jar with size 7.7939453 KB
Download finished for jarsplitter-1.1.2.jar !
Global percentage >63%
Downloading file asm-analysis-6.1.1.jar with size 31.229492 KB
Download finished for asm-analysis-6.1.1.jar !
Global percentage >64%
Downloading file binarypatcher-1.0.12.jar with size 16.104492 KB
Download finished for binarypatcher-1.0.12.jar !
Global percentage >66%
Downloading file commons-io-2.4.jar with size 180.80078 KB
Download finished for commons-io-2.4.jar !
Global percentage >68%
Downloading file coremods-4.0.6.jar with size 24.856445 KB
Download finished for coremods-4.0.6.jar !
Global percentage >70%
Downloading file jopt-simple-5.0.4.jar with size 76.31445 KB
Download finished for jopt-simple-5.0.4.jar !
Global percentage >71%
Downloading file asm-9.1.jar with size 118.93555 KB
Download finished for asm-9.1.jar !
Global percentage >73%
Downloading file asm-analysis-9.1.jar with size 33.4541 KB
Download finished for asm-analysis-9.1.jar !
Global percentage >75%
Downloading file asm-commons-9.1.jar with size 70.93848 KB
Download finished for asm-commons-9.1.jar !
Global percentage >77%
Downloading file asm-tree-9.1.jar with size 51.427734 KB
Download finished for asm-tree-9.1.jar !
Global percentage >78%
Downloading file asm-util-9.1.jar with size 82.694336 KB
Download finished for asm-util-9.1.jar !
Global percentage >80%
Downloading file log4j-core-2.11.2.jar with size 1.5540934MB
Download finished for log4j-core-2.11.2.jar !
Global percentage >82%
Downloading file opencsv-2.3.jar with size 19.362305 KB
Download finished for opencsv-2.3.jar !
Global percentage >84%
Downloading file jsr305-3.0.2.jar with size 19.46875 KB
Download finished for jsr305-3.0.2.jar !
Global percentage >85%
Downloading file jline-2.14.6.jar with size 262.48047 KB
Download finished for jline-2.14.6.jar !
Global percentage >87%
Downloading file modlauncher-8.0.9.jar with size 123.23828 KB
Download finished for modlauncher-8.0.9.jar !
Global percentage >89%
Downloading file installertools-1.1.11.jar with size 53.030273 KB
Download finished for installertools-1.1.11.jar !
Global percentage >91%
Downloading file lzma-java-1.3.jar with size 49.844727 KB
Download finished for lzma-java-1.3.jar !
Global percentage >92%
Downloading file typetools-0.8.3.jar with size 15.063477 KB
Download finished for typetools-0.8.3.jar !
Global percentage >94%
Downloading file asm-6.1.1.jar with size 105.71484 KB
Download finished for asm-6.1.1.jar !
Global percentage >96%
Downloading file nashorn-core-compat-15.1.1.1.jar with size 2.0924158MB
Download finished for nashorn-core-compat-15.1.1.1.jar !
Global percentage >98%
Downloading file antlr4-runtime-4.9.1.jar with size 329.94922 KB
Download finished for antlr4-runtime-4.9.1.jar !
Global percentage >10%
Downloading file maven-resolver-provider-3.8.1.jar with size 64.68262 KB
Download finished for maven-resolver-provider-3.8.1.jar !
Global percentage >10%
Downloading file maven-resolver-connector-basic-1.6.2.jar with size 44.652344 KB
Download finished for maven-resolver-connector-basic-1.6.2.jar !
Global percentage >10%
Downloading file maven-resolver-transport-http-1.6.2.jar with size 42.594727 KB
Download finished for maven-resolver-transport-http-1.6.2.jar !
Loading mappings
Loading mappings... 0%
Loading mappings... 10%
Loading mappings... 20%
Loading mappings... 30%
Loading mappings... 40%
Loading mappings... 50%
0 packages, 5447 classes, 21481 fields, 38359 methods
Remapping final jar
Remapping jar... 0%
Remapping jar... 10%
Remapping jar... 20%
Remapping jar... 30%
Remapping jar... 40%
Remapping jar... 50%
Remapping jar... 60%
Remapping jar... 70%
Remapping jar... 80%
Remapping jar... 90%
Remapping jar... 100%
[00:54:52][INFO]: you are running the latest version of LoliServer, no need to update
[04:55:48][main][INFO]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.8, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[04:55:48][main][INFO]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_282 by Oracle Corporation
[04:55:49][main][INFO]: Added Lets Encrypt root certificates as additional trust
[04:55:49][main][INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/container/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[04:55:51][main][INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 13:0 token recognition error at: '`'
Init CreativeCore coremods ...
[04:55:52][main][ERROR]: Mixin config wyml.mixins.json does not specify "minVersion" property
[04:55:52][main][ERROR]: Mixin config minetogether.mixins.json does not specify "minVersion" property
[04:55:52][main][INFO]: Successfully loaded Mixin Connector [vazkii.botania.common.MixinConnector]
[04:55:52][main][INFO]: Successfully loaded Mixin Connector [com.leobeliik.extremesoundmuffler.MixinConnector]
[04:55:52][main][INFO]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[04:55:52][main][INFO]: Launching target 'fmlserver' with arguments [--gameDir, .]
[04:55:53][main][WARN]: Reference map 'lemonlib.refmap.json' for lemonlib.mixins.json could not be read. If this is a development environment you can ignore this message
[04:55:53][main][WARN]: Reference map 'rhino-forge-refmap.json' for rhino.mixins.json could not be read. If this is a development environment you can ignore this message
[04:55:53][main][INFO]: Loaded rule configuration file for RoadRunner: 83 options available, 3 override(s) found
[04:55:53][main][INFO]: Transforming method: getMaxAirSupply net.minecraft.entity.Entity
[04:55:53][main][INFO]: Patching ItemStack#onItemUse
[04:55:54][main][WARN]: Force-disabling mixin 'alloc.chunk_ticking.ChunkTicketManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by user configuration) disables it and children
[04:55:54][main][WARN]: Force-disabling mixin 'alloc.chunk_ticking.ServerChunkManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by user configuration) disables it and children
[04:55:54][main][WARN]: Force-disabling mixin 'chunk.no_locking.PalettedContainerMixin' as rule 'mixin.chunk.no_locking' (added by mods [roadrunner]) disables it and children
[04:55:54][main][WARN]: Force-disabling mixin 'entity.data_tracker.no_locks.DataTrackerMixin' as rule 'mixin.entity.data_tracker.no_locks' (added by mods [roadrunner]) disables it and children
[04:55:54][main][INFO]: Transforming method: canBreatheUnderwater net.minecraft.entity.LivingEntity
[04:55:54][main][INFO]: Transforming method: decreaseAirSupply net.minecraft.entity.LivingEntity
[04:55:54][main][INFO]: Transforming method: increaseAirSupply net.minecraft.entity.LivingEntity
[04:55:54][main][INFO]: Patching LivingEntity#attackEntityFrom
[04:55:54][main][INFO]: Transforming method: travel net.minecraft.entity.LivingEntity
[04:55:55][main][INFO]: Patching DataPackRegistries#<init>
[04:55:55][main][INFO]: Patching LootTableManager#apply
Exception in thread "main" [04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoSuchFieldError: nestHostClass
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.util.asm.ClassNodeAdapter.getNestHostClass(ClassNodeAdapter.java:52)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.util.LanguageFeatures.scanClassFeatures(LanguageFeatures.java:117)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.util.LanguageFeatures.scan(LanguageFeatures.java:97)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.mixin.transformer.MixinInfo$State.validateClassFeatures(MixinInfo.java:357)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.mixin.transformer.MixinInfo$State.validate(MixinInfo.java:334)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:913)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:801)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:567)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at java.lang.Class.forName0(Native Method)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at java.lang.Class.forName(Class.java:348)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:66)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:63)
[04:55:55][main][INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraftforge.server.ServerMain.main(ServerMain.java:60)
[04:56:03][pool-4-thread-1][INFO]: Config at /home/container/config/wyml.json has changed, reloaded!
**Mod list(模组列表) :** {List of your mods. You can also use /getmodlist command on your server}

FTB OceanBlock 1.2.0

**Plugin list(插件列表) :** {List of your plugins. You can also use /getpluginlist command on your server}

ban item
betterrtp
clearlag + timer
dcintegration 
elitelootbox
holodisplays
luckperms
nuvotifier
playerlands
ultimate auto restart

**Description of issue(描述) :** {Give all details about your issue}
 Cant get anywhere passed that error for some reason that I dont know
No crash just text there. It freezes up and refused to crash unless killed

**Comment by Xplodin** [comment]
Restarting does the same thing 
  


Restart

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
