### ISSUE TITLE
[1.16.5] CMI Errored command cmi killall

### ISSUE THREAD

**Issue by TheKlimoT** [Loli-Server/LoliServer1.16#281]
Minecraft Version(我的世界版本) : 1.16.5

LoliServer buildVersion(构建版本) : 185

Operating System(操作系统) : Debian 10
Logs : no logs

Mod list(模组列表) : -

Plugin list(插件列表) : CMI

Description of issue(描述) : I write /cmi killall -monsters, and errored

Hastebin: https://www.toptal.com/developers/hastebin/zunodazuli.properties

**Comment by Kotori0629** [comment]
Can you use https://paste.loliidc.cn/   ?

**Comment by TheKlimoT** [comment]
https://paste.loliidc.cn/?93fe54a9e0dc31c1#2C6Dgs8gkhCKA9UAY8DDi3CXeKtC6nyeEwWKX53nxFwc

**Comment by Kotori0629** [comment]
I can't repeat this problem. It may be caused by a mod. I hope you can check which mod it is

**Comment by TheKlimoT** [comment]
Really?
Caused by: java.lang.NullPointerException
        at moe.loliserver.entity.CraftCustomEntity.getCustomName(CraftCustomEntity.java:42) ~[forge:?]
        at com.Zrips.CMI.commands.list.killall.perform(killall.java:266) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[forge:?]
        ... 20 more

**Comment by TheKlimoT** [comment]
That is, Mohist works with this team and all the mods that are on LoliServer, and you say that the problem is something else?
