### ISSUE TITLE
[1.16] 夸克MOD装了崩溃

### ISSUE THREAD

**Issue by haozaizai1** [Loli-Server/LoliServer1.16#286]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

------------
# Chinese: 
// 如果你需要得到LoliServer开发组的帮助, 请通过Discord或者QQ联系我们, 或者: 
// Step 1: 提交这个Crashreport中的文本至 https://paste.ubuntu.com
// Step 2: 创建一个新的Issues至LoliServer的Github仓库, 地址: https://github.com/Loli-Server/LoliServer1.16/issues
# English and other: 
// If you need to LoliServer Development Group help, Contact us at discord or: 
// Step 1: Submit this CrashReport to https://paste.ubuntu.com/
// Step 2: Create a new issues to LoliServer's Github repos, Link: https://github.com/Loli-Server/LoliServer1.16/issues
------------

Time: 21-11-29 下午1:59
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:121) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[LoliServer-1.16.5-185-server.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:86) [LoliServer-1.16.5-185-server.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:83) [LoliServer-1.16.5-185-server.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:80) [LoliServer-1.16.5-185-server.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[LoliServer-1.16.5-185-server.jar:36.2] {}
-- MOD quark --
Details:
	Mod File: [夸克]Quark-r2.4-320.jar
	Failure message: Quark (quark) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/inventory/ContainerScreen for invalid dist DEDICATED_SERVER
	Mod Version: r2.4-320
	Mod Issue URL: https://github.com/Vazkii/Quark
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/inventory/ContainerScreen for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[LoliServer-1.16.5-185-server.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_301] {}
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_301] {}
	at vazkii.quark.base.module.ModuleFinder.loadModule(ModuleFinder.java:40) ~[quark:r2.4-320] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_301] {re:computing_frames}
	at java.util.stream.SortedOps$RefSortingSink.end(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.stream.Sink$ChainedReference.end(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_301] {}
	at vazkii.quark.base.module.ModuleFinder.findModules(ModuleFinder.java:34) ~[quark:r2.4-320] {re:classloading}
	at vazkii.quark.base.module.ModuleLoader.findModules(ModuleLoader.java:52) ~[quark:r2.4-320] {re:classloading,pl:runtimedistcleaner:A}
	at vazkii.quark.base.module.ModuleLoader.start(ModuleLoader.java:38) ~[quark:r2.4-320] {re:classloading,pl:runtimedistcleaner:A}
	at vazkii.quark.base.proxy.CommonProxy.start(CommonProxy.java:36) ~[quark:r2.4-320] {re:classloading}
	at vazkii.quark.base.Quark.<init>(Quark.java:30) ~[quark:r2.4-320] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_301] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_301] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_301] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:82) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_301] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	LoliServer Version: 1.16.5-185
	Operating System: Windows Server 2019 (amd64) version 10.0
	Java Version: 1.8.0_301, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4875295016 bytes (4649 MB) / 6304563200 bytes (6012 MB) up to 6304563200 bytes (6012 MB)
	CPUs: 4
	JVM Flags: 3 total; -Xmx6144M -Xms6144M -Xss512K
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/LoliServer-1.16.5-185-server.jar object_holder_definalize PLUGINSERVICE 
		/LoliServer-1.16.5-185-server.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/LoliServer-1.16.5-185-server.jar capability_inject_definalize PLUGINSERVICE 
		/LoliServer-1.16.5-185-server.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/LoliServer-1.16.5-185-server.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.19
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.19-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.2.1.296.jar                   |Tinkers' Construct            |tconstruct                    |3.2.1.296           |CREATE_REG|Manifest: NOSIGNATURE
		[农夫乐事]FarmersDelight-1.16.5-0.5.1.jar             |Farmer's Delight              |farmersdelight                |1.16.5-0.5.1        |CREATE_REG|Manifest: NOSIGNATURE
		[星辉魔法]astralsorcery-1.16-1.16.5-1.13.12.jar       |Astral Sorcery                |astralsorcery                 |1.16.5-1.13.12      |CREATE_REG|Manifest: 45:2b:0a:49:6b:65:3b:39:a9:dd:d2:5b:55:7f:82:47:a5:1d:7a:cc:7f:a8:69:73:72:53:6f:57:4d:b2:1a:b7
		[魔法艺术]mana-and-artifice-1.5.0.10 (1).jar          |Mana and Artifice             |mana-and-artifice             |1.5.0.10            |CREATE_REG|Manifest: NOSIGNATURE
		pamhc2trees-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.1               |CREATE_REG|Manifest: NOSIGNATURE
		[农夫乐事拓展]pharmacist-V5.3.jar                       |Pharmacist                    |pharmacist                    |1                   |CREATE_REG|Manifest: NOSIGNATURE
		[矿工头盔]mining_helmet-1.16.5-2.0.1.jar              |Mining Helmet                 |mining_helmet                 |2.0.1               |CREATE_REG|Manifest: NOSIGNATURE
		[1.16.5]+ComicsBubblesChat-1.3.0.jar              |Comics Bubbles Chat           |comicsbubbleschat             |version             |CREATE_REG|Manifest: NOSIGNATURE
		pamhc2crops-1.16.3-1.0.2.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |CREATE_REG|Manifest: NOSIGNATURE
		[猫咪装饰]nekoration-1.16.X-1.4.2.jar                 |Nekoration                    |nekoration                    |1.4.2               |CREATE_REG|Manifest: NOSIGNATURE
		AoA3-3.5.4-1.16.5 (1).jar                         |Advent of Ascension           |aoa3                          |3.5.4               |CREATE_REG|Manifest: NOSIGNATURE
		[简单农业]simplefarming-1.16.5-1.3.8.jar              |Simple Farming                |simplefarming                 |1.16.5-1.3.8        |CREATE_REG|Manifest: NOSIGNATURE
		[植物魔法]Botania-1.16.5-420.jar                      |Botania                       |botania                       |1.16.5-420          |CREATE_REG|Manifest: NOSIGNATURE
		[真实钓鱼]fishingreal-1.16.3-1.0.0.jar                |Fishing Real                  |fishingreal                   |1.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		[中式工坊] ChineseWorkshop-1.16.3-3.2.1.jar           |ChineseWorkshop               |chineseworkshop               |3.2.1               |CREATE_REG|Manifest: NOSIGNATURE
		Kiwi-1.16.5-3.5.2.jar                             |Kiwi                          |kiwi                          |3.5.2               |CREATE_REG|Manifest: NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.4.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |CREATE_REG|Manifest: NOSIGNATURE
		[小汽车]car-1.16.5-1.0.17.jar                        |Ultimate Car Mod              |car                           |1.16.5-1.0.17       |CREATE_REG|Manifest: NOSIGNATURE
		[阿图姆前置]curios-forge-1.16.5-4.0.5.3.jar            |Curios API                    |curios                        |1.16.5-4.0.5.3      |CREATE_REG|Manifest: NOSIGNATURE
		[机械动力前置]flywheel-1.16-0.2.4.jar                   |Flywheel                      |flywheel                      |1.16-0.2.4          |CREATE_REG|Manifest: NOSIGNATURE
		[女仆]touhoulittlemaid-1.16.5-1.0.0-beta-hotfix (1).|Touhou Little Maid            |touhou_little_maid            |NONE                |CREATE_REG|Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.127.jar                         |Mantle                        |mantle                        |1.6.127             |CREATE_REG|Manifest: NOSIGNATURE
		[机械动力]create-mc1.16.5_v0.3.2g.jar                 |Create                        |create                        |v0.3.2g             |CREATE_REG|Manifest: NOSIGNATURE
		[手册]Patchouli-1.16.4-53.2.jar                     |Patchouli                     |patchouli                     |1.16.4-53.2         |CREATE_REG|Manifest: NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.2.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |CREATE_REG|Manifest: NOSIGNATURE
		[交易站前置]SilveroakOutpost-Forge-1.16.5-0.3.5-Beta.ja|Silveroak Outpost             |silveroakoutpost              |0.3.5-Beta          |CREATE_REG|Manifest: NOSIGNATURE
		[懒人厨房]CookingForBlockheads_1.16.5-9.3.4.jar       |Cooking for Blockheads        |cookingforblockheads          |9.3.4               |CREATE_REG|Manifest: NOSIGNATURE
		[夸克前置]AutoRegLib-1.6-49.jar                       |AutoRegLib                    |autoreglib                    |1.6-49              |CREATE_REG|Manifest: NOSIGNATURE
		[旅行者背包]TravelersBackpack-1.16.5-5.4.5.jar         |Traveler's Backpack           |travelersbackpack             |5.4.5               |CREATE_REG|Manifest: NOSIGNATURE
		[储物抽屉] StorageDrawers-1.16.3-8.3.0.jar            |Storage Drawers               |storagedrawers                |8.3.0               |CREATE_REG|Manifest: NOSIGNATURE
		[饮水]WaterSource-1.1.36-beta-1.16.5.jar            |Water Source                  |watersource                   |1.1.36-beta-1.16.5  |CREATE_REG|Manifest: NOSIGNATURE
		[交易站]Barter-Forge-1.16.5-0.2.7-Beta.jar           |Barter                        |barter                        |0.2.7-Beta          |CREATE_REG|Manifest: NOSIGNATURE
		[家具]cfm-7.0.0pre22-1.16.3 (1).jar                 |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre22         |CREATE_REG|Manifest: NOSIGNATURE
		[额外植物魔法]ExtraBotany-r1.2-68 (2).jar               |ExtraBotany                   |extrabotany                   |1.0                 |CREATE_REG|Manifest: NOSIGNATURE
		[星辉前置]observerlib-1.16.5-1.5.3.jar                |ObserverLib                   |observerlib                   |1.16.5-1.5.3        |CREATE_REG|Manifest: NOSIGNATURE
		CraftTweaker-1.16.5-7.1.2.456.jar                 |CraftTweaker                  |crafttweaker                  |7.1.2.456           |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.19-universal.jar                |Forge                         |forge                         |36.2.19             |CREATE_REG|Manifest: NOSIGNATURE
		[夸克]Quark-r2.4-320.jar                            |Quark                         |quark                         |r2.4-320            |ERROR     |Manifest: NOSIGNATURE
		[阿图姆]Atum-1.16.5-2.2.8 (1).jar                    |Atum 2                        |atum                          |1.16.5-2.2.8        |CREATE_REG|Manifest: NOSIGNATURE
		[苹果皮]appleskin-forge-mc1.16.x-2.2.0.jar           |AppleSkin                     |appleskin                     |mc1.16.4-2.2.0      |CREATE_REG|Manifest: NOSIGNATURE
		[水产养殖]Aquaculture-1.16.5-2.1.21.jar               |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.21       |CREATE_REG|Manifest: NOSIGNATURE
		[暮色森林]twilightforest-1.16.5-4.0.546-universal.jar |The Twilight Forest           |twilightforest                |NONE                |CREATE_REG|Manifest: NOSIGNATURE
		[魔法艺术前置]geckolib-forge-1.16.5-3.0.56.jar          |GeckoLib                      |geckolib3                     |3.0.56              |CREATE_REG|Manifest: NOSIGNATURE
		[更多箱子]ironchest-1.16.5-11.2.13 (1).jar            |Iron Chests                   |ironchest                     |1.16.5-11.2.13      |CREATE_REG|Manifest: NOSIGNATURE
		[喝酒]drinkbeer-1.16.5-2.3.5.jar                    |Drink Beer                    |drinkbeer                     |2.3.5               |CREATE_REG|Manifest: NOSIGNATURE
	Crash Report UUID: e25ab258-b6fd-4e68-9e5b-447786e7765d
	CraftBukkit Information: 
   Running: 
   Failed to handle CraftCrashReport: craftbukkit not runs

**Comment by Kotori0629** [comment]
更新夸克到321版本, 作者修复了这个问题
[https://github.com/VazkiiMods/Quark/issues/3476](https://github.com/VazkiiMods/Quark/issues/3476)
