### ISSUE TITLE
[1.16] Console Spam with GriefDefender

### ISSUE THREAD

**Issue by ahdg6** [Loli-Server/LoliServer1.16#64]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :**LoliServer-1.16.5-38-server.jar"

**Operating System(操作系统) :** CentOS

**Concerned mod / plugin(有关的插件/Mod) :** GriefDefender (Clean install)

**Logs :** [20:40:20] [Server thread/ERROR] [Minecraft/]: Could not pass event BlockPhysicsEvent to GriefDefender v2.0.0-DEV
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[forge:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [forge:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574) [forge:?]
	at net.minecraft.world.World.func_190524_a(World.java:482) [?:?]
	at net.minecraft.world.World.func_195593_d(World.java:433) [?:?]
	at net.minecraft.world.server.ServerWorld.func_230547_a_(ServerWorld.java:1611) [?:?]
	at net.minecraft.world.World.markAndNotifyBlock(World.java:362) [?:?]
	at net.minecraft.world.World.func_241211_a_(World.java:334) [?:?]
	at net.minecraft.world.World.func_180501_a(World.java:270) [?:?]
	at net.minecraft.world.World.func_175656_a(World.java:421) [?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227033_a_(AbstractBlock.java:620) [?:?]
	at net.minecraft.world.server.ServerWorld.func_205338_b(ServerWorld.java:693) [?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$12075/0x0000000099905270.accept(Unknown Source) [?:?]
	at net.minecraft.world.server.ServerTickList.func_205365_a(SourceFile:84) [?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:417) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1017) [?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:333) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:926) [?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:759) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$9784/0x00000000991b25d0.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException
	at com.griefdefender.listener.BlockEventHandler.onBlockNotify(BlockEventHandler.java:556) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor109.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[forge:?]
	... 23 more

**Comment by Kotori0629** [comment]
And, Do you have GriefDefender v2.0.0-DEV this plugin? please give me.

**Comment by ahdg6** [comment]
[griefdefender-bukkit-1.5.10.jar.zip](https://github.com/Loli-Server/LoliServer1.16/files/6825128/griefdefender-bukkit-1.5.10.jar.zip)
https://github.com/bloodmc/GriefDefender

**Comment by ahdg6** [comment]
It has been fixed by author in GD2.0-DEV-TEST46.jar

**Comment by Kotori0629** [comment]
Thanks for Author
