### ISSUE TITLE
我的mod列表中加入了某npcmod以后 显示机械动力读取错误 似乎不是由单一mod造成的 我单独使用机械动力和npcmod并没有冲突

### ISSUE THREAD

**Issue by fkyah3** [Loli-Server/LoliServer1.16#87]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

------------
# Chinese: 
// 如果你需要得到LoliServer开发组的帮助, 请通过Discord或者QQ联系我们, 或者: 
// Step 1: 提交这个Crashreport中的文本至 https://paste.ubuntu.com
// Step 2: 创建一个新的Issues至LoliServer的Github仓库, 地址: https://github.com/Loli-Server/LoliServer1.16/issues
# English and other: 
// If you need to LoliServer Development Group help, Contact us at discord or: 
// Step 1: Submit this CrashReport to https://paste.ubuntu.com/
// Step 2: Create a new issues to LoliServer's Github repos, Link: https://github.com/Loli-Server/LoliServer1.16/issues
------------

Time: 21-7-26 下午1:19
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:121) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281] {re:computing_frames}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[server.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:66) [server.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:63) [server.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:60) [server.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {re:classloading}
-- MOD create --
Details:
	Caused by 0: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
		at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
		at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
		at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.0.9.jar:8.0.9+86+master.3cf110c] {}
		at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
		at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281] {}
		at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281] {}
		at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_281] {}
		at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:76) ~[forge:?] {re:classloading}
		at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_281] {}
		at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:63) ~[forge:?] {re:classloading}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:92) ~[forge:36.1] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_281] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_281] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_281] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_281] {}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_281] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_281] {}

	Caused by 1: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [taterzens.common.mixins.json:ServerPlayNetworkHandlerMixin_MsgEditor] from phase [DEFAULT] in config [taterzens.common.mixins.json] FAILED during APPLY
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
		at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
		at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
		at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.0.9.jar:8.0.9+86+master.3cf110c] {}
		at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
		at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281] {}
		at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281] {}
		at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_281] {}
		at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:76) ~[forge:?] {re:classloading}
		at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_281] {}
		at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:63) ~[forge:?] {re:classloading}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:92) ~[forge:36.1] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_281] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_281] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_281] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_281] {}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_281] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_281] {}

	Mod File: 机械动力.jar
	Failure message: Create (create) has failed to load correctly
		org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	Mod Version: v0.3.2b for 1.16.5
	Mod Issue URL: https://github.com/Creators-of-Create/Create/issues
	Exception message: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onMessage could not find any targets matching 'Lnet/minecraft/network/play/ServerPlayNetHandler;func_244548_c(Ljava/lang/String;)V' in net.minecraft.network.play.ServerPlayNetHandler. Using refmap taterzens-common-refmap.json [PREINJECT Applicator Phase -> taterzens.common.mixins.json:ServerPlayNetworkHandlerMixin_MsgEditor -> Prepare Injections ->  -> handler$zzh000$onMessage(Ljava/lang/String;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
Stacktrace:
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {re:classloading}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {re:classloading}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {re:classloading}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {re:classloading}
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at sun.reflect.GeneratedConstructorAccessor26.newInstance(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_281] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {re:classloading}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.0.9.jar:8.0.9+86+master.3cf110c] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281] {}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281] {}
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_281] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:76) ~[forge:?] {re:classloading}
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_281] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:63) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:92) ~[forge:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_281] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_281] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	LoliServer Version: 1.16.5-38
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1549585584 bytes (1477 MB) / 2094661632 bytes (1997 MB) up to 2094661632 bytes (1997 MB)
	CPUs: 12
	JVM Flags: 14 total; -Xmx2100M -Xms2100M -Xss256k -XX:PermSize=256m -XX:MaxPermSize=256m -XX:NewSize=1024m -XX:MaxNewSize=1024m -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+UseFastAccessorMethods -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=100 -XX:+CMSParallelRemarkEnabled -XX:ParallelGCThreads=20
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/server.jar object_holder_definalize PLUGINSERVICE 
		/server.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/server.jar capability_inject_definalize PLUGINSERVICE 
		/server.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/server.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.32
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.32-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: NOSIGNATURE
		农夫乐视FarmersDelight-1.16.5-0.4.5.jar               |Farmer's Delight              |farmersdelight                |1.16.5-0.4.5        |CREATE_REG|Manifest: NOSIGNATURE
		现代家具Modernxl+[1.16.5]+Fireplaces+update.jar       |Modernxl                      |minecraftmodernxl             |1.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		自定义npctaterzens-1.1.0-forge.jar                   |Taterzens                     |taterzens                     |1.1.0               |CREATE_REG|Manifest: NOSIGNATURE
		现代家具Furniture_Pack_1.1_1.16.4.jar                 |Realism Mats Furniture Pack   |realism_mats_furniture_pack   |1.1.0               |CREATE_REG|Manifest: NOSIGNATURE
		火把放置优化torchslabmod-1.16.4_v1.6.19.jar             |Torch Slab Mod                |torchslabmod                  |1.6.18              |CREATE_REG|Manifest: NOSIGNATURE
		更多生物群系BiomesOPlenty-1.16.5-13.1.0.477-universal.ja|Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.477   |CREATE_REG|Manifest: NOSIGNATURE
		16x材质优化Variant16x-1.16.5-v0.21.4_beta_pre6.jar    |Variant16x                    |variant16x                    |0.21.4_beta_pre6    |CREATE_REG|Manifest: NOSIGNATURE
		垃圾桶前置supermartijn642corelib-1.0.10-mc1.16.5.jar   |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.10              |CREATE_REG|Manifest: NOSIGNATURE
		更流畅的加载smoothboot-forge-1.16.4-1.2.2.jar           |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |CREATE_REG|Manifest: NOSIGNATURE
		金刚鹦鹉的窗户mcw-windows-1.0.3-mc1.16.5.jar             |Macaw's Windows               |mcwwindows                    |1.0.3               |CREATE_REG|Manifest: NOSIGNATURE
		火花cpu监视spark-forge.jar                            |spark                         |spark                         |1.6.0               |CREATE_REG|Manifest: NOSIGNATURE
		flywheel-1.16-0.1.1.jar                           |Flywheel                      |flywheel                      |1.16-0.1.1          |CREATE_REG|Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.2      |CREATE_REG|Manifest: NOSIGNATURE
		机械动力.jar                                          |Create                        |create                        |v0.3.2b for 1.16.5  |ERROR     |Manifest: NOSIGNATURE
		指路石Waystones_1.16.5-7.6.2.jar                     |Waystones                     |waystones                     |7.6.2               |CREATE_REG|Manifest: NOSIGNATURE
		墙纸工艺WallpaperCraft-1.16.3-1.4.6.jar               |Wallpapercraft                |wallpapercraft                |1.4.5               |CREATE_REG|Manifest: NOSIGNATURE
		TerraForged-1.16.5-0.2.12.jar                     |TerraForged                   |terraforged                   |0.2.12              |CREATE_REG|Manifest: 7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |CREATE_REG|Manifest: NOSIGNATURE
		journeymap-1.16.5-5.7.1.jar                       |Journeymap                    |journeymap                    |5.7.1               |CREATE_REG|Manifest: NOSIGNATURE
		装饰方块decorative_blocks-1.16.4-1.7.2.jar            |Decorative Blocks             |decorative_blocks             |1.7.2               |CREATE_REG|Manifest: NOSIGNATURE
		载具前置obfuscate-0.6.2-1.16.3.jar                    |Obfuscate                     |obfuscate                     |0.6.2               |CREATE_REG|Manifest: e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		载具vehicle-mod-0.45.2-1.16.3.jar                   |MrCrayfish's Vehicle Mod      |vehicle                       |0.45.2              |CREATE_REG|Manifest: NOSIGNATURE
		Chunk+Pregenerator-V1.16-3.0.5.jar                |Chunk Pregenerator            |chunkpregen                   |V1.16-3.0.5         |CREATE_REG|Manifest: NOSIGNATURE
		前置Bookshelf-1.16.5-10.1.11.jar                    |Bookshelf                     |bookshelf                     |10.1.11             |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		更多工艺添加buildersaddition-1.16.5-20210517a.jar       |Builders Crafts & Addition    |buildersaddition              |1.16.5-20210517a    |CREATE_REG|Manifest: NOSIGNATURE
		金刚鹦鹉的屋顶mcw-roofs-2.0.1-mc1.16.5-4.jar             |Macaw's Roofs                 |mcwroofs                      |2.0.1               |CREATE_REG|Manifest: NOSIGNATURE
		小龙虾先生的家具cfm-7.0.0pre22-1.16.3.jar                 |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre22         |CREATE_REG|Manifest: NOSIGNATURE
		反正是个前置mapperbase-1.16.5-2.4.0.0.jar               |Mapper Base                   |mapperbase                    |1.16.5-2.4.0.0      |CREATE_REG|Manifest: NOSIGNATURE
		润式工艺确信embellishcraft-1.16.5-3.4.0.0.jar           |EmbellishCraft                |embellishcraft                |1.16.5-3.4.0.0      |CREATE_REG|Manifest: NOSIGNATURE
		roadstuff-1.16.5-4.3.0.jar                        |Road Stuff                    |roadstuff                     |1.16.5-4.3.0        |CREATE_REG|Manifest: NOSIGNATURE
		凿子2Chisel-MC1.16.5-2.0.0-alpha.3.jar              |Chisel                        |chisel                        |MC1.16.5-2.0.0-alpha|CREATE_REG|Manifest: NOSIGNATURE
		金刚鹦鹉的家具mcw-furniture-2.0.1-mc1.16.5.jar           |Macaw's Furniture             |mcwfurnitures                 |2.0.1               |CREATE_REG|Manifest: NOSIGNATURE
		垃圾桶trashcans-1.0.10-mc1.16.5.jar                  |Trash Cans                    |trashcans                     |1.0.10              |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.1.32-universal.jar                |Forge                         |forge                         |36.1.32             |CREATE_REG|Manifest: NOSIGNATURE
		派蒙apaimon-r1.0-4.jar                              |A Paimon                      |apaimon                       |1.0                 |CREATE_REG|Manifest: NOSIGNATURE
		xk的建筑2xkdeco_0.2.1.jar                            |XK's Deco                     |xkdeco                        |0.2.0               |CREATE_REG|Manifest: NOSIGNATURE
		supplementaries-1.16.5-0.14.5.jar                 |Supplementaries               |supplementaries               |1.16.5-0.14.0       |CREATE_REG|Manifest: NOSIGNATURE
		音乐制作xercamusic-1.16.5-1.4.jar                     |Xerca's Music Maker Mod       |xercamusic                    |1.16.5-1.4          |CREATE_REG|Manifest: NOSIGNATURE
		前置selene-1.16.5-1.5.jar                           |Selene                        |selene                        |1.16.5-1.0          |CREATE_REG|Manifest: NOSIGNATURE
		金刚鹦鹉的路灯mcw-lights-1.0.0-mc1.16.5.jar              |Macaw's Lights and Lamps      |mcwlights                     |1.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		领地台territory-1.16.3+-0.4.5.jar                    |Territory Mod                 |territory                     |0.4.5               |CREATE_REG|Manifest: NOSIGNATURE
	Crash Report UUID: 2e03b386-65e9-48f6-bf6e-3d09be3bf7dd
	CraftBukkit Information: 
   Running: 
   Failed to handle CraftCrashReport: craftbukkit not runs

**Comment by Kotori0629** [comment]
请删除服务端中的部分辅助mod后重试

**Comment by fkyah3** [comment]
> 请删除服务端中的部分辅助mod后重试

Variant16x删除之后恢复正常 感谢
